### ISSUE TITLE
addition of voice channel ticketing 

### ISSUE THREAD

**Issue by ghost** [CarelessInternet/Ticketer#118]
Please check out https://github.com/mic0ishere/mi-bot/blob/main/commands/tickets/voiceticket.js i think addition of voice channels would help promote your bot + maybe a dashboard of sorts like helper.gg but the above voice channel ticket is a cool idea

**Comment by CarelessInternet** [comment]
I am closing this as not planned because I have made the choice to make Ticketer stick to threads as much as possible. This suggestion thus is irrelevant to the bot.
